/// Service to provide simple definitions for common words used in anagram exercises
class WordDefinitionService {
  /// Get a simple definition for a word
  /// Returns a brief, easy-to-understand definition suitable for cognitive exercises
  static String? getDefinition(String word) {
    final upperWord = word.toUpperCase();
    return _definitions[upperWord];
  }

  /// Simple, clear definitions for common words
  static final Map<String, String> _definitions = {
    // 3-letter words
    'CAT': 'A small furry pet animal that meows',
    'DOG': 'A loyal pet animal that barks',
    'CAR': 'A vehicle with four wheels for driving',
    'SUN': 'The bright star that gives us light and heat',
    'BOX': 'A container for storing things',
    'CUP': 'A small container for drinking',
    'BED': 'Furniture for sleeping',
    'HAT': 'Something worn on the head',
    'BAG': 'A container for carrying things',
    'PEN': 'A writing tool with ink',
    'KEY': 'A tool for locking and unlocking',
    'EGG': 'Food laid by chickens',
    'RUN': 'To move fast on foot',
    'EAT': 'To consume food',
    'SEE': 'To look at with your eyes',
    'FLY': 'To move through the air',

    // 4-letter words
    'CAVE': 'A large natural hole in a mountain or cliff',
    'TREE': 'A tall plant with a trunk, branches, and leaves',
    'BOOK': 'Printed pages bound together for reading',
    'FISH': 'An animal that lives and swims in water',
    'BIRD': 'An animal with feathers that can fly',
    'HAND': 'The part of your body at the end of your arm',
    'FEET': 'The parts of your body you stand on',
    'HEAD': 'The top part of your body with your brain',
    'DOOR': 'An entrance you open and close',
    'RAIN': 'Water that falls from clouds',
    'SNOW': 'White frozen water that falls in winter',
    'WIND': 'Moving air you can feel',
    'MOON': 'The bright object in the night sky',
    'STAR': 'A bright light in the night sky',
    'FIRE': 'Hot flames that give light and heat',
    'HOME': 'The place where you live',
    'FOOD': 'What you eat to stay alive',
    'BALL': 'A round object used in games',
    'GAME': 'An activity played for fun',
    'PLAY': 'To have fun or do an activity',
    'WALK': 'To move by putting one foot in front of the other',
    'TALK': 'To speak with someone',
    'WORK': 'A job or task you do',
    'TIME': 'Hours, minutes, and seconds',
    'YEAR': 'A period of 365 days',
    'FACE': 'The front part of your head',
    'NAME': 'What someone or something is called',
    'BLUE': 'The color of the sky',
    'WARM': 'Having pleasant heat',
    'COLD': 'Having low temperature',
    'DARK': 'Having no light',
    'HELP': 'To assist someone',

    // 5-letter words
    'HOUSE': 'A building where people live',
    'WATER': 'The clear liquid you drink',
    'APPLE': 'A round red or green fruit',
    'CHAIR': 'Furniture for sitting',
    'TABLE': 'Furniture with a flat top for eating or working',
    'SHIRT': 'Clothing worn on the upper body',
    'PHONE': 'A device for talking to people far away',
    'BREAD': 'A baked food made from flour',
    'GRASS': 'Green plants that cover lawns',
    'CLOUD': 'White or gray mass floating in the sky',
    'BEACH': 'Sandy shore by the ocean',
    'RIVER': 'A long flowing body of water',
    'MUSIC': 'Sounds arranged in a pleasing way',
    'HAPPY': 'Feeling good and joyful',
    'SMILE': 'An expression showing you are happy',
    'SLEEP': 'To rest with your eyes closed',
    'DREAM': 'Images in your mind while sleeping',
    'MONEY': 'Coins and bills used to buy things',
    'STORE': 'A place where you buy things',
    'WATCH': 'A small clock worn on your wrist',
    'CLOCK': 'A device that shows the time',
    'PLANT': 'A living thing that grows in soil',
    'HEART': 'The organ that pumps blood',
    'BRAIN': 'The organ in your head for thinking',
    'VOICE': 'The sound you make when speaking',
    'SOUND': 'Something you hear',
    'LIGHT': 'Brightness that lets you see',
    'QUIET': 'Making little or no noise',
    'WORLD': 'The earth and all people on it',
    'PEACE': 'A state without war or fighting',
    'POWER': 'Strength or energy',
    'MAGIC': 'Mysterious tricks or supernatural events',
    'HORSE': 'A large animal people ride',
    'MOUSE': 'A small furry animal with a long tail',
    'WHEEL': 'A circular object that rotates',
    'TRUCK': 'A large vehicle for carrying goods',
    'TRAIN': 'A vehicle that runs on railroad tracks',
    'PLANE': 'A flying vehicle with wings',
    'KNIFE': 'A sharp tool for cutting',
    'SPOON': 'A utensil for eating soup or cereal',
    'PLATE': 'A flat dish for holding food',
    'GLASS': 'A container for drinking, or material you can see through',
    'LEMON': 'A sour yellow fruit',
    'GRAPE': 'A small round fruit that grows in bunches',
    'SWEET': 'Having a pleasant taste like sugar',
    'BREAD': 'Food made from baked dough',
    'NIGHT': 'The time when it is dark outside',
    'TODAY': 'This current day',
    'EARLY': 'Near the beginning of a time period',
    'FIRST': 'Coming before all others',
    'LAUGH': 'To make sounds when something is funny',
    'DANCE': 'To move your body to music',
    'PAINT': 'Colored liquid for decorating',
    'WRITE': 'To make letters and words on paper',
    'FRONT': 'The part that faces forward',
    'BELOW': 'At a lower position',
    'ABOVE': 'At a higher position',
    'UNDER': 'Beneath or below something',
    'ROUND': 'Shaped like a circle or ball',
    'SHARP': 'Having a thin cutting edge',
    'CLEAN': 'Free from dirt',
    'CLOSE': 'Near or shut',
    'RIGHT': 'Correct or the opposite of left',
    'WRONG': 'Not correct',
    'SMALL': 'Not big or large',
    'LARGE': 'Big in size',
    'QUICK': 'Fast or rapid',
    'BROWN': 'A color like wood or chocolate',
    'WHITE': 'The color of snow',
    'BLACK': 'The darkest color',
    'GREEN': 'The color of grass and leaves',
    'YOUNG': 'Not old',
    'CHILD': 'A young person',
    'WOMAN': 'An adult female person',
    'PLACE': 'A location or spot',
    'THING': 'An object or item',
    'STONE': 'A small piece of rock',
    'METAL': 'A hard shiny material like iron',
    'PAPER': 'Thin material for writing or wrapping',
    'FIELD': 'An open area of land',
    'FLOOR': 'The surface you walk on inside',
    'SPACE': 'An empty area or the universe',
    'NORTH': 'The direction toward the top of a map',
    'SOUTH': 'The direction toward the bottom of a map',
    'FRESH': 'New or recently made',
    'QUIET': 'Making little noise',
    'READY': 'Prepared to do something',
  };
}
