// Mocks generated by Mockito 5.4.6 from annotations
// in brain_tests/test/unit/features/brain_exercises_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_tests/domain/entities/cognitive_exercise.dart' as _i4;
import 'package:brain_tests/domain/entities/enums.dart' as _i5;
import 'package:brain_tests/domain/repositories/cognitive_exercise_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CognitiveExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCognitiveExerciseRepository extends _i1.Mock
    implements _i2.CognitiveExerciseRepository {
  MockCognitiveExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CognitiveExercise>> getAllExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CognitiveExercise>>.value(
            <_i4.CognitiveExercise>[]),
      ) as _i3.Future<List<_i4.CognitiveExercise>>);

  @override
  _i3.Future<List<_i4.CognitiveExercise>> getExercisesByType(
          _i5.ExerciseType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.CognitiveExercise>>.value(
            <_i4.CognitiveExercise>[]),
      ) as _i3.Future<List<_i4.CognitiveExercise>>);

  @override
  _i3.Future<List<_i4.CognitiveExercise>> getExercisesByDifficulty(
          _i5.ExerciseDifficulty? difficulty) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByDifficulty,
          [difficulty],
        ),
        returnValue: _i3.Future<List<_i4.CognitiveExercise>>.value(
            <_i4.CognitiveExercise>[]),
      ) as _i3.Future<List<_i4.CognitiveExercise>>);

  @override
  _i3.Future<List<_i4.CognitiveExercise>> getCompletedExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CognitiveExercise>>.value(
            <_i4.CognitiveExercise>[]),
      ) as _i3.Future<List<_i4.CognitiveExercise>>);

  @override
  _i3.Future<_i4.CognitiveExercise?> getExerciseById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i3.Future<_i4.CognitiveExercise?>.value(),
      ) as _i3.Future<_i4.CognitiveExercise?>);

  @override
  _i3.Future<int> insertExercise(_i4.CognitiveExercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertExercise,
          [exercise],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateExercise(_i4.CognitiveExercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [exercise],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteExercise(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.ExerciseType, double>> getAverageScoresByType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScoresByType,
          [],
        ),
        returnValue: _i3.Future<Map<_i5.ExerciseType, double>>.value(
            <_i5.ExerciseType, double>{}),
      ) as _i3.Future<Map<_i5.ExerciseType, double>>);

  @override
  _i3.Future<List<_i4.CognitiveExercise>> getRecentExercises(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExercises,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.CognitiveExercise>>.value(
            <_i4.CognitiveExercise>[]),
      ) as _i3.Future<List<_i4.CognitiveExercise>>);
}
