// Mocks generated by Mockito 5.4.6 from annotations
// in brain_tests/test/unit/features/mood_tracking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_tests/data/datasources/database.dart' as _i5;
import 'package:brain_tests/domain/entities/mood_entry.dart' as _i4;
import 'package:brain_tests/domain/repositories/mood_entry_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MoodEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoodEntryRepository extends _i1.Mock
    implements _i2.MoodEntryRepository {
  MockMoodEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MoodEntry>> getAllMoodEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllMoodEntries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.MoodEntry>>.value(<_i4.MoodEntry>[]),
      ) as _i3.Future<List<_i4.MoodEntry>>);

  @override
  _i3.Future<List<_i4.MoodEntry>> getMoodEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodEntriesByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i4.MoodEntry>>.value(<_i4.MoodEntry>[]),
      ) as _i3.Future<List<_i4.MoodEntry>>);

  @override
  _i3.Future<_i4.MoodEntry?> getMoodEntryById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMoodEntryById,
          [id],
        ),
        returnValue: _i3.Future<_i4.MoodEntry?>.value(),
      ) as _i3.Future<_i4.MoodEntry?>);

  @override
  _i3.Future<_i4.MoodEntry?> getMoodEntryByDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodEntryByDate,
          [date],
        ),
        returnValue: _i3.Future<_i4.MoodEntry?>.value(),
      ) as _i3.Future<_i4.MoodEntry?>);

  @override
  _i3.Future<int> insertMoodEntry(_i4.MoodEntry? moodEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMoodEntry,
          [moodEntry],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateMoodEntry(_i4.MoodEntry? moodEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMoodEntry,
          [moodEntry],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteMoodEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMoodEntry,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.MoodLevel, int>> getMoodDistribution() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodDistribution,
          [],
        ),
        returnValue:
            _i3.Future<Map<_i5.MoodLevel, int>>.value(<_i5.MoodLevel, int>{}),
      ) as _i3.Future<Map<_i5.MoodLevel, int>>);

  @override
  _i3.Future<List<_i4.MoodEntry>> getRecentMoodEntries({int? limit = 7}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMoodEntries,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.MoodEntry>>.value(<_i4.MoodEntry>[]),
      ) as _i3.Future<List<_i4.MoodEntry>>);

  @override
  _i3.Future<double> getAverageWellnessScore() => (super.noSuchMethod(
        Invocation.method(
          #getAverageWellnessScore,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}
