// Mocks generated by Mockito 5.4.6 from annotations
// in brain_plan/test/unit/features/smart_reminders_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_plan/domain/entities/reminder.dart' as _i4;
import 'package:brain_plan/domain/repositories/reminder_repository.dart' as _i2;
import 'package:brain_plan/domain/types/types.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i2.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Reminder>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<List<_i4.Reminder>> getActiveReminders() => (super.noSuchMethod(
        Invocation.method(
          #getActiveReminders,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<List<_i4.Reminder>> getRemindersByType(_i5.ReminderType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemindersByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<List<_i4.Reminder>> getUpcomingReminders() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingReminders,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<List<_i4.Reminder>> getOverdueReminders() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueReminders,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<List<_i4.Reminder>> getCompletedReminders({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedReminders,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Reminder>>.value(<_i4.Reminder>[]),
      ) as _i3.Future<List<_i4.Reminder>>);

  @override
  _i3.Future<_i4.Reminder?> getReminderById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReminderById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Reminder?>.value(),
      ) as _i3.Future<_i4.Reminder?>);

  @override
  _i3.Future<int> insertReminder(_i4.Reminder? reminder) => (super.noSuchMethod(
        Invocation.method(
          #insertReminder,
          [reminder],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateReminder(_i4.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [reminder],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> markReminderCompleted(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markReminderCompleted,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> snoozeReminder(
    int? id,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #snoozeReminder,
          [
            id,
            duration,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
