// Mocks generated by Mockito 5.4.6 from annotations
// in brain_tests/test/unit/presentation/providers/weekly_mci_test_count_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_tests/data/datasources/database.dart' as _i5;
import 'package:brain_tests/domain/entities/assessment.dart' as _i4;
import 'package:brain_tests/domain/repositories/assessment_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AssessmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssessmentRepository extends _i1.Mock
    implements _i2.AssessmentRepository {
  MockAssessmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Assessment>> getAllAssessments() => (super.noSuchMethod(
        Invocation.method(
          #getAllAssessments,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<List<_i4.Assessment>> getAssessmentsByType(
          _i5.AssessmentType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssessmentsByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<List<_i4.Assessment>> getAssessmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssessmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<_i4.Assessment?> getAssessmentById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAssessmentById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Assessment?>.value(),
      ) as _i3.Future<_i4.Assessment?>);

  @override
  _i3.Future<int> insertAssessment(_i4.Assessment? assessment) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAssessment,
          [assessment],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateAssessment(_i4.Assessment? assessment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssessment,
          [assessment],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAssessment(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssessment,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.AssessmentType, double>> getAverageScoresByType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScoresByType,
          [],
        ),
        returnValue: _i3.Future<Map<_i5.AssessmentType, double>>.value(
            <_i5.AssessmentType, double>{}),
      ) as _i3.Future<Map<_i5.AssessmentType, double>>);

  @override
  _i3.Future<List<_i4.Assessment>> getRecentAssessments({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentAssessments,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);
}
