// Mocks generated by Mockito 5.4.6 from annotations
// in brain_plan/test/unit/presentation/screens/exports_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_plan/data/datasources/database.dart' as _i5;
import 'package:brain_plan/domain/entities/assessment.dart' as _i4;
import 'package:brain_plan/domain/entities/cognitive_exercise.dart' as _i9;
import 'package:brain_plan/domain/entities/mood_entry.dart' as _i7;
import 'package:brain_plan/domain/repositories/assessment_repository.dart'
    as _i2;
import 'package:brain_plan/domain/repositories/cognitive_exercise_repository.dart'
    as _i8;
import 'package:brain_plan/domain/repositories/mood_entry_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AssessmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssessmentRepository extends _i1.Mock
    implements _i2.AssessmentRepository {
  MockAssessmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Assessment>> getAllAssessments() => (super.noSuchMethod(
        Invocation.method(
          #getAllAssessments,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<List<_i4.Assessment>> getAssessmentsByType(
          _i5.AssessmentType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssessmentsByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<List<_i4.Assessment>> getAssessmentsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssessmentsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);

  @override
  _i3.Future<_i4.Assessment?> getAssessmentById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAssessmentById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Assessment?>.value(),
      ) as _i3.Future<_i4.Assessment?>);

  @override
  _i3.Future<int> insertAssessment(_i4.Assessment? assessment) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAssessment,
          [assessment],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateAssessment(_i4.Assessment? assessment) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAssessment,
          [assessment],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAssessment(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAssessment,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.AssessmentType, double>> getAverageScoresByType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScoresByType,
          [],
        ),
        returnValue: _i3.Future<Map<_i5.AssessmentType, double>>.value(
            <_i5.AssessmentType, double>{}),
      ) as _i3.Future<Map<_i5.AssessmentType, double>>);

  @override
  _i3.Future<List<_i4.Assessment>> getRecentAssessments({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentAssessments,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Assessment>>.value(<_i4.Assessment>[]),
      ) as _i3.Future<List<_i4.Assessment>>);
}

/// A class which mocks [MoodEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoodEntryRepository extends _i1.Mock
    implements _i6.MoodEntryRepository {
  MockMoodEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.MoodEntry>> getAllMoodEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllMoodEntries,
          [],
        ),
        returnValue: _i3.Future<List<_i7.MoodEntry>>.value(<_i7.MoodEntry>[]),
      ) as _i3.Future<List<_i7.MoodEntry>>);

  @override
  _i3.Future<List<_i7.MoodEntry>> getMoodEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodEntriesByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i7.MoodEntry>>.value(<_i7.MoodEntry>[]),
      ) as _i3.Future<List<_i7.MoodEntry>>);

  @override
  _i3.Future<_i7.MoodEntry?> getMoodEntryById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMoodEntryById,
          [id],
        ),
        returnValue: _i3.Future<_i7.MoodEntry?>.value(),
      ) as _i3.Future<_i7.MoodEntry?>);

  @override
  _i3.Future<_i7.MoodEntry?> getMoodEntryByDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodEntryByDate,
          [date],
        ),
        returnValue: _i3.Future<_i7.MoodEntry?>.value(),
      ) as _i3.Future<_i7.MoodEntry?>);

  @override
  _i3.Future<int> insertMoodEntry(_i7.MoodEntry? moodEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMoodEntry,
          [moodEntry],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateMoodEntry(_i7.MoodEntry? moodEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMoodEntry,
          [moodEntry],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteMoodEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMoodEntry,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.MoodLevel, int>> getMoodDistribution() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodDistribution,
          [],
        ),
        returnValue:
            _i3.Future<Map<_i5.MoodLevel, int>>.value(<_i5.MoodLevel, int>{}),
      ) as _i3.Future<Map<_i5.MoodLevel, int>>);

  @override
  _i3.Future<List<_i7.MoodEntry>> getRecentMoodEntries({int? limit = 7}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMoodEntries,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i7.MoodEntry>>.value(<_i7.MoodEntry>[]),
      ) as _i3.Future<List<_i7.MoodEntry>>);

  @override
  _i3.Future<double> getAverageWellnessScore() => (super.noSuchMethod(
        Invocation.method(
          #getAverageWellnessScore,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}

/// A class which mocks [CognitiveExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCognitiveExerciseRepository extends _i1.Mock
    implements _i8.CognitiveExerciseRepository {
  MockCognitiveExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i9.CognitiveExercise>> getAllExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i9.CognitiveExercise>>.value(
            <_i9.CognitiveExercise>[]),
      ) as _i3.Future<List<_i9.CognitiveExercise>>);

  @override
  _i3.Future<List<_i9.CognitiveExercise>> getExercisesByType(
          _i5.ExerciseType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i9.CognitiveExercise>>.value(
            <_i9.CognitiveExercise>[]),
      ) as _i3.Future<List<_i9.CognitiveExercise>>);

  @override
  _i3.Future<List<_i9.CognitiveExercise>> getExercisesByDifficulty(
          _i5.ExerciseDifficulty? difficulty) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByDifficulty,
          [difficulty],
        ),
        returnValue: _i3.Future<List<_i9.CognitiveExercise>>.value(
            <_i9.CognitiveExercise>[]),
      ) as _i3.Future<List<_i9.CognitiveExercise>>);

  @override
  _i3.Future<List<_i9.CognitiveExercise>> getCompletedExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i9.CognitiveExercise>>.value(
            <_i9.CognitiveExercise>[]),
      ) as _i3.Future<List<_i9.CognitiveExercise>>);

  @override
  _i3.Future<_i9.CognitiveExercise?> getExerciseById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i3.Future<_i9.CognitiveExercise?>.value(),
      ) as _i3.Future<_i9.CognitiveExercise?>);

  @override
  _i3.Future<int> insertExercise(_i9.CognitiveExercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertExercise,
          [exercise],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> updateExercise(_i9.CognitiveExercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [exercise],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteExercise(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.ExerciseType, double>> getAverageScoresByType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageScoresByType,
          [],
        ),
        returnValue: _i3.Future<Map<_i5.ExerciseType, double>>.value(
            <_i5.ExerciseType, double>{}),
      ) as _i3.Future<Map<_i5.ExerciseType, double>>);

  @override
  _i3.Future<List<_i9.CognitiveExercise>> getRecentExercises(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExercises,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i9.CognitiveExercise>>.value(
            <_i9.CognitiveExercise>[]),
      ) as _i3.Future<List<_i9.CognitiveExercise>>);
}
