// File generated by FlutterFire CLI.
// This is a template configuration for Firebase.
// In production, replace these with your actual Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example (using Firebase project configuration):
/// Replace the template values below with your actual Firebase project settings
/// obtained from the Firebase Console (https://console.firebase.google.com)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final options = _getCurrentPlatformOptions();
    _validateFirebaseConfig(options);
    return options;
  }

  static FirebaseOptions _getCurrentPlatformOptions() {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Validates Firebase configuration to ensure template values were replaced
  static void _validateFirebaseConfig(FirebaseOptions options) {
    final errors = <String>[];

    // Check for template/placeholder values
    if (options.apiKey.startsWith('your-') || options.apiKey.isEmpty) {
      errors.add('apiKey contains template value: "${options.apiKey}"');
    }

    if (options.appId.contains('123456789') || options.appId.contains('abcdef123456')) {
      errors.add('appId contains template value: "${options.appId}"');
    }

    if (options.messagingSenderId == '123456789') {
      errors.add('messagingSenderId contains template value: "${options.messagingSenderId}"');
    }

    if (options.projectId.startsWith('your-firebase-project') || options.projectId.isEmpty) {
      errors.add('projectId contains template value: "${options.projectId}"');
    }

    if (options.storageBucket?.startsWith('your-firebase-project') ?? false) {
      errors.add('storageBucket contains template value: "${options.storageBucket}"');
    }

    // If any validation errors found, throw with detailed message
    if (errors.isNotEmpty) {
      throw Exception(
        '\n'
        '═══════════════════════════════════════════════════════════════\n'
        '  Firebase Configuration Error\n'
        '═══════════════════════════════════════════════════════════════\n'
        '\n'
        'The Firebase configuration contains template/placeholder values.\n'
        'Please update lib/firebase_options.dart with your actual Firebase\n'
        'project configuration.\n'
        '\n'
        'Issues found:\n'
        '${errors.map((e) => '  • $e').join('\n')}\n'
        '\n'
        'To fix this:\n'
        '  1. Go to https://console.firebase.google.com\n'
        '  2. Select or create your Firebase project\n'
        '  3. Add your Flutter app to the project\n'
        '  4. Run: flutterfire configure\n'
        '     OR manually update the values in lib/firebase_options.dart\n'
        '\n'
        'For detailed instructions, see:\n'
        'https://firebase.google.com/docs/flutter/setup\n'
        '═══════════════════════════════════════════════════════════════\n',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-firebase-project-id',
    authDomain: 'your-firebase-project-id.firebaseapp.com',
    storageBucket: 'your-firebase-project-id.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
    iosBundleId: 'com.example.brainplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
    iosBundleId: 'com.example.brainplan.macos',
  );
}

/// Instructions for setting up Firebase:
///
/// 1. Go to https://console.firebase.google.com
/// 2. Create a new project or select existing project
/// 3. Add your Flutter app to the project
/// 4. Download the configuration files:
///    - google-services.json for Android (place in android/app/)
///    - GoogleService-Info.plist for iOS (place in ios/Runner/)
/// 5. Run `flutter packages pub run build_runner build` to generate configuration
/// 6. Replace the template values above with your actual project configuration
/// 7. Enable Analytics, Crashlytics, and Performance Monitoring in Firebase Console
///
/// For detailed setup instructions, see:
/// https://firebase.google.com/docs/flutter/setup