import 'package:drift/drift.dart' hide isNotNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:brain_tests/data/datasources/database.dart';
import 'package:brain_tests/domain/entities/enums.dart'; // Ensure Enums are available

// We need to simulate the database class to test migration logic conceptually
// or use the actual generated class once available.
// Since we can't compile tests against non-existent columns, we will:
// 1. Define the test structure.
// 2. Comment out the specific column checks until generation is done.

void main() {
  group('Database Schema Migration (UUID & Sync)', () {
    late AppDatabase database;

    setUp(() {
      database = AppDatabase.memory();
    });

    tearDown(() {
      database.close();
    });

    test('Tables should have sync columns (Compilation Check)', () async {
      // This test serves as a compilation check once we implement the columns.
      // If the columns don't exist on the generated class, this test won't compile.
      
      // Verify we can access the new columns
      // This proves they exist on the Table class
      expect(database.userProfileTable.uuid, isNotNull);
      expect(database.userProfileTable.syncStatus, isNotNull);
      expect(database.userProfileTable.lastUpdatedAt, isNotNull);
    });

    test('New rows should have default SyncStatus.pendingInsert', () async {
      // Insert a row
      await database.into(database.dailyGoalsTable).insert(
        DailyGoalsTableCompanion.insert(
          date: DateTime.now(),
          // uuid is auto-generated by clientDefault
          // syncStatus should default to pendingInsert (1)
        )
      );

      final row = await database.select(database.dailyGoalsTable).getSingle();
      expect(row.syncStatus, equals(SyncStatus.pendingInsert));
      expect(row.uuid, isNotNull);
      expect(row.uuid.length, greaterThan(10)); // Basic UUID check
    });
  });
}
